---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: post-test-cleanup
spec:
  workspaces:
    - name: repository
  stepTemplate:
    env:
      - name: PULP_CLI_CONFIG
        value: /etc/pulp-access/cli.toml
      - name: PULP_TOOL_PATH
        value: $(workspaces.repository.path)/source
  steps:
    - name: post-test-cleanup
      image: registry.fedoraproject.org/fedora:45@sha256:7c96770c3676e4e61a3c0e258f7488c1ac723557ff4c10a24a0125ae330d0e10
      script: |
        #!/usr/bin/env sh
        set -euo pipefail
        dnf install -y python3 pulp-cli

        "${PULP_TOOL_PATH}/e2e/post-test-cleanup.py" --config "${PULP_CLI_CONFIG}"

      volumeMounts:
        - name: cli-toml-volume
          mountPath: /etc/pulp-access
          readOnly: true
  volumes:
    - name: cli-toml-volume
      secret:
        secretName: pulp-access
        items:
          - key: cli.toml
            path: cli.toml
