apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pulp-e2e-testing
  labels:
    appstudio.openshift.io/application: tooling
    appstudio.openshift.io/component: pulp-e2e-testing
    pipelines.appstudio.openshift.io/type: build
spec:
  params:
    - name: git-url
      description: URL of the Git repository to clone
      type: string
    - name: revision
      description: Git revision to checkout
      type: string
    - name: output-image
      description: Fully qualified image name for the output
      type: string
    - name: image-expires-after
      description: Image expiration time
      type: string
      default: 5d
  workspaces:
    - name: test
      description: Workspace for test artifacts
    - name: repository
      description: Workspace for cloned repository
    - name: git-auth
      description: Git authentication credentials
      optional: true
  tasks:
    - name: init
      taskRef:
        params:
          - name: name
            value: init
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-init:0.4.3@sha256:fb17ececc359d7e330395d6a562eacbf0089776697ffe1b10c08f91273e6b2c0
          - name: kind
            value: task
        resolver: bundles
    - name: clone-repository
      runAfter:
        - init
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.revision)
      taskRef:
        params:
          - name: name
            value: git-clone
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-git-clone:0.2.5@sha256:4a6567757596e348fe2505f7e2cc0286ad98a32d9b510d1a44d0bf6ed6df5469
          - name: kind
            value: task
        resolver: bundles
      workspaces:
        - name: output
          workspace: repository
        - name: basic-auth
          workspace: git-auth
    - name: run-e2e-test-suite
      runAfter:
        - clone-repository
      taskRef:
        resolver: git
        params:
          - name: revision
            value: $(params.revision)
          - name: url
            value: $(params.git-url)
          - name: pathInRepo
            value: ".tekton/tasks/run-e2e-test-suite.yaml"
      workspaces:
        - name: test
          workspace: test
        - name: repository
          workspace: repository
  finally:
    - name: post-test-cleanup
      taskRef:
        resolver: git
        params:
          - name: revision
            value: $(params.revision)
          - name: url
            value: $(params.git-url)
          - name: pathInRepo
            value: ".tekton/tasks/post-test-cleanup.yaml"
      workspaces:
        - name: repository
          workspace: repository
